### ISSUE TITLE
something wrong with 'complie.m'

### ISSUE THREAD

**Issue by bucktoothsir** [cvondrick/ihog#2]
I have read the read.me then I tried to run 'complie.m' but failed.
The console showed information that:

 Error: Could not find the compiler "g++-4" on the DOS path. 
         Use mex -setup to configure your environment properly. 

I used matlab2013 and vs2010 for the complier. All of them are 32-bit.I can complie other files successfully.
So can you help me?

**Comment by olivernina** [comment]
You just need to change the default compiler setting in compile.m for spams. By default it is set to 'gcc' you just change it to 'mex' and it should work.

**Comment by ffarahnakg** [comment]
Thank you @olivernina . It worked by changing the default compiler to 'mex'.
